NUM_CELLS = 20

CELL_SIZE = (20, 20)

HEALTHBAR_SIZE = (CELL_SIZE[0] * 0.8, CELL_SIZE[1] * 0.1)
HEALTHBAR_OFFSET = (CELL_SIZE[0] * 0.1, -CELL_SIZE[1] * 0.4)

OFFSET = 40

SCREEN_SIZE = (
                CELL_SIZE[0] * NUM_CELLS + 2 * OFFSET,
                CELL_SIZE[1] * NUM_CELLS + 2 * OFFSET
              )

INITIAL_PLAYER1_POS = (0, 0)
INITIAL_PLAYER2_POS = (18, 18)

TIME_DELAY = 0.5
